# Generated by Django 4.1 on 2022-08-31 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('en curso', 'En Curso'), ('finalizada', 'Finalizada')], default='en curso', max_length=15)),
                ('estudiantes', models.ManyToManyField(blank=True, to='app.estudiante')),
            ],
            options={
                'ordering': ('fecha_inicio',),
            },
        ),
        migrations.CreateModel(
            name='Adelanto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('tiempo', models.IntegerField()),
                ('estudiantes', models.ManyToManyField(blank=True, to='app.estudiante')),
                ('tarea', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.tarea')),
            ],
        ),
    ]
