# Generated by Django 4.1 on 2022-08-31 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_adelanto_descripcion_alter_tarea_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelanto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='adelanto',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='app.estudiante', verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='adelanto',
            name='tarea',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.tarea', verbose_name='Tarea asignada'),
        ),
        migrations.AlterField(
            model_name='adelanto',
            name='tiempo',
            field=models.IntegerField(verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='adelanto',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, to='app.estudiante', verbose_name='Responsables'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
