# Generated by Django 4.1 on 2022-09-01 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_adelanto_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelanto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
