# Generated by Django 4.1 on 2022-09-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_adelanto_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adelanto',
            options={'ordering': ['-fecha']},
        ),
    ]
