# Generated by Django 4.1 on 2022-09-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_adelanto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adelanto',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, default=None, to='app.estudiante', verbose_name='Participantes'),
        ),
    ]
